
export const countryOptions = [
  {
    id: 1,
    label: 'Angola',
    checked: false,
  },
  {
    id: 2,
    label: 'Australia',
    checked: false,
  },
  {
    id: 3,
    label: 'Austria',
    checked: false,
  },
  {
    id: 4,
    label: 'Bahrain',
    checked: false,
  }
]

// export const countryOptions = [
//   'Angola',
//   'Australia',
//   'Austria',
//   'Bahrain',
//   'Bangladesh',
//   'Belarus',
//   'Belgium',
//   'Brazil',
//   'Cambodia',
//   'Cameroon',
//   'Canada',
//   'Chile',
//   'Colombia',
//   'Costa Rica',
//   'Denmark',
//   'Dominican Republic',
//   'Egypt',
//   'Ethiopia',
//   'Finland',
//   'France',
//   'Georgia',
//   'Germany',
//   'Greece',
//   'Hong Kong',
//   'Hungary',
//   'Indonesia',
//   'Ireland',
//   'Israel',
//   'Italy',
//   'Japan',
//   'Jordan',
//   'Kenya',
//   'Kuwait',
//   'Malaysia',
//   'Mauritius',
//   'Mexico',
//   'Morocoo',
//   'Myanmar',
//   'Nepal',
//   'Netherlands',
//   'New Zealand',
//   'Nicaragua',
//   'Nigeria',
//   'Norway',
//   'Oman',
//   'Pakistan',
//   'Panama',
//   'Paraguay',
//   'Peru',
//   'Philippines',
//   'Poland',
//   'Portugal',
//   'Romania',
//   'Russia',
//   'Saudi Arabia',
//   'Senegal',
//   'Singapore',
//   'Slovakia',
//   'South Africa',
//   'South Korea',
//   'Spain',
//   'Sri Lanka',
//   'Sweden',
//   'Switzerland',
//   'Taiwan',
//   'Tanzania',
//   'Thailand',
//   'Tunisia',
//   'Turkiye',
//   'Uganda',
//   'Ukraine',
//   'United Arab Emirates',
//   'United Kingdom',
//   'United States',
//   'Venezuela',
//   'Vietnam',
//   'Zambia',
//   'Zimbabwe'
// ]